# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Croquet Australia
email: admin@croquet-australia.com.au
description: > # this means to ignore newlines until "baseurl:"
  Australian Croquet Association trading as Croquet Australia & Gateball Australia 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://croquet-australia.com.au" # the base hostname & protocol for your site
permalink: /news/:year/:month/:title
paginate: 10
paginate_path: "/news/page:num/"
gems: [jekyll-paginate]

# Build settings
# todo: what are the markdown alternatives
markdown: kramdown

exclude:
- node_modules/